---
title: "Virginia OLS Regression"
author: "Elisabeth Wasserman"
date: "2024-06-20"
output: html_document
---
```{r}
library(dplyr)
library(here)
```


```{r import}
virginia_2018_2022 = read.csv(here("Data/merged_data", "virginia_2018_2022.csv"), sep = ",", header = TRUE)
appalachia_2018_2022 = read.csv(here("Data/merged_data", "appalachia_2018_2022.csv"), sep = ",", header = TRUE)
```

```{r ruc}
# Assume 'data' is your dataframe and 'ruc_code' is the column with the Rural-Urban Continuum Codes
virginia_2018_2022 <- virginia_2018_2022 %>%
  mutate(ruc_group = case_when(
    RUCC_2023 %in% 1:3 ~ "Metro",
    RUCC_2023 %in% 4:9 ~ "Non-Metro",

    TRUE ~ "Unknown"  # This line handles any data that might not fit the defined categories
  ))
virginia_2018_2022$ruc_group = as.factor(virginia_2018_2022$ruc_group)
```

```{r try}
virginia_ols_dod_1822 <- lm(DOD_death_rate ~ MHP_ratio + PCP_ratio + Median_household_income + Avg_mentally_unhealthy_days + Excessive_drinking + Teen_birth_rate + Poor_fair_health + Adult_smoking + Children_in_poverty + Severe_housing_problems + total_DSW + BA_higher_ratio + below_poverty_ratio + unemployed_pop_pe, data = virginia_2018_2022)

summary(virginia_ols_dod_1822)

virginia_ols_dod_1822_test1 <- lm(DOD_death_rate ~ MHP_ratio + Avg_mentally_unhealthy_days+ Teen_birth_rate + total_DSW + BA_higher_ratio + unemployed_pop_pe+ ruc_group + as.factor(Year), data = virginia_2018_2022)

summary(virginia_ols_dod_1822_test1)

virginia_ols_dod_1822_test2 <- lm(DOD_death_rate ~ below_poverty_ratio + BA_higher_ratio + unemployed_pop_pe+ ruc_group + as.factor(Year), data = virginia_2018_2022)

summary(virginia_ols_dod_1822_test2)

virginia_ols_dod_1822_test3 <- lm(DOD_death_rate ~ below_poverty_ratio + BA_higher_ratio + unemployed_pop_pe + total_DSW + Teen_birth_rate + ruc_group + as.factor(Year) , data = virginia_2018_2022)

summary(virginia_ols_dod_1822_test3)

#virginia_ols_dod_1519 <- lm(DOD_death_rate ~ BA_higher_ratio + unemployed_pop_pe + Median_household_income, data = virginia_2015_2019)

#virginia_ols_edvisits_1519 <- lm(Annual.Overdose.Visits ~ BA_higher_ratio + unemployed_pop_pe + Median_household_income, data = virginia_2015_2019)
```


```{r}
library(leaps)
regFull <- regsubsets(DOD_death_rate ~ MHP_ratio + Avg_mentally_unhealthy_days + Excessive_drinking +  Poor_fair_health + Adult_smoking + Severe_housing_problems + total_DSW + BA_higher_ratio + below_poverty_ratio + unemployed_pop_pe + as.factor(RUCC_2023)+as.factor(Year), data = virginia_2018_2022, method = 'exhaustive', nbest = 1)

output = summary(regFull, all.best = TRUE)

criterionMat <- cbind(output$rsq,output$adjr2,output$cp, output$bic)
colnames(criterionMat) = c('R2', 'AdjR2', 'Cp','BIC')

resultsMat = cbind(output$outmat, round(criterionMat,3))
resultsMat
```


```{r}
virginia_ols_1 <- lm(DOD_death_rate ~ below_poverty_ratio + BA_higher_ratio + unemployed_pop_pe+as.factor(RUCC_2023)+as.factor(Year), data = virginia_2018_2022)

summary(virginia_ols_1)

library(stargazer)
stargazer(virginia_ols_1 , type = "text")
```
```{r}
virginia_ols_2 <- lm(DOD_death_rate ~ below_poverty_ratio + BA_higher_ratio + unemployed_pop_pe + total_male_pop+ as.factor(RUCC_2023)+as.factor(Year), data = virginia_2018_2022)

summary(virginia_ols_2)

library(stargazer)
stargazer(virginia_ols_2, type = "text")
```

```{r}
virginia_ols_3 <- lm(DOD_death_rate ~ below_poverty_ratio + BA_higher_ratio + unemployed_pop_pe + total_male_pop + total_white+ +total_black+as.factor(RUCC_2023)+as.factor(Year), data = virginia_2018_2022)

summary(virginia_ols_3)

library(stargazer)
stargazer(virginia_ols_3, type = "text")
```
```{r}
appalachia_ols_1 <- lm(DOD_death_rate ~ below_poverty_ratio + BA_higher_ratio + unemployed_pop_pe+as.factor(RUCC_2023)+as.factor(Year), data = appalachia_2018_2022)

summary(appalachia_ols_1)

library(stargazer)
stargazer(appalachia_ols_1 , type = "text")
```

```{r}
appalachia_ols_2 <- lm(DOD_death_rate ~ below_poverty_ratio + BA_higher_ratio + unemployed_pop_pe + total_male_pop+ as.factor(RUCC_2023)+as.factor(Year), data = appalachia_2018_2022)

summary(appalachia_ols_2)

library(stargazer)
stargazer(appalachia_ols_2, type = "text")
```

```{r}
suppressd_va <- virginia_2018_2022 %>% #186 out of 665 is suppressed
  filter(is.na(DOD_death_rate))

suppressd_appa <- appalachia_2018_2022 %>%  #382 out of 2115 is suppressed
  filter(is.na(DOD_death_rate))
```

