---
title: "Merged Map Datasets"
author: "Elisabeth Wasserman"
date: "2024-06-06"
output: html_document
---

```{r}
library(here)
library(dplyr)
library(tidycensus)
library(tidyverse)
library(sf)
library(leaflet)
```
# Shp Data too large to upload on Github
```{r map data}
#use tigris library to get county shapefiles
options(tigris_use_cache = TRUE)
appalachian_states <- c("AL", "GA", "KY", "MD", "MS", "NY", "NC", "OH", "PA", "SC", "TN", "VA", "WV")

all_counties <- list()

for (state in appalachian_states) {
  state_counties <- counties(state = state, cb = TRUE)
  all_counties[[state]] <- state_counties
}

# Combine all counties into a single sf object
us_counties <- do.call(rbind, all_counties)

us_counties$GEOID = as.integer(us_counties$GEOID)
```

```{r}
test <- va_counties %>%
  left_join(virginia_2018_2022, by = c("GEOID" = "FIPS"), multiple = "all")
```

# Map with Shapefile Merge
```{r, eval=FALSE}
#create FIPS for shapefile
counties_shapefile$FIPS = paste(counties_shapefile$STATEFP, counties_shapefile$COUNTYFP, sep="")
counties_shapefile$FIPS <- as.integer(counties_shapefile$FIPS)

#appalachia mapping and variables
map_appalachia_2018_2022 = right_join(counties_shapefile, appalachia_2018_2022, by = c("FIPS"), multiple = "all")

#virginia mapping and variables
map_virginia_2018_2022 = right_join(counties_shapefile, virginia_2018_2022, by = c("FIPS"), multiple = "all")
```

#Map Data Export 
```{r, eval=FALSE}
#write.csv(map_appalachia_2018_2022, 
         # file = here("Data/merged_data", "map_virginia_2018_2022.csv"),
         # row.names = FALSE) 

#write.csv(map_virginia_2018_2022, 
         # file = here("Data/merged_data", "map_appalachia_2018_2022.csv"),
        #  row.names = FALSE) 
```



