---
title: "corr_app_DODvsBelow_Poverty_1822"
author: "Brynna Wert"
date: "2024-06-18"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(viridis)
```

```{r}
corr_data <- appalachia_2018_2022 %>%
  mutate(
    Below_poverty_ratio = as.numeric(as.character(below_poverty_ratio)),
    DOD_death_rate = as.numeric(as.character(DOD_death_rate))
  ) %>%
  select(below_poverty_ratio, DOD_death_rate) %>%
  mutate(DOD_percent = DOD_death_rate * 100)
 
# Remove rows with NA values
corr_data <- na.omit(corr_data)
```

```{R}
# Create a scatterplot with a regression line using viridis color palette
ggplot(corr_data, aes(x = below_poverty_ratio, y = DOD_percent)) +
  geom_point(color = viridis(256)[50], size = 2, alpha = 0.7) +  # Use a consistent viridis color for points with transparency
  geom_smooth(method = "lm", color = viridis(256)[200], size = 1.5, se = FALSE) +  # Add a prominent regression line
  labs(title = "Appalachian Below Poverty Rate and DOD Death Rate (2018-2022)",
       caption = "Data obtained from the American Community Survey and National Center for Health Statistics (CDC)",
       x = "Population Below Poverty (%)",
       y = "DOD Rate (%)") +
  theme_minimal(base_size = 15) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 15),
    axis.title = element_text(face = "bold"),
    panel.grid.major = element_line(color = "grey80"),
    panel.grid.minor = element_blank(),
    legend.position = "none"  # Remove the legend
  )
```